"use client";

/**
 * Onboarding Content Component
 *
 * Smart Onboarding Flow with Premium UI/UX:
 * 1. Checks user profile via /api/user/profile (includes business + subscription).
 * 2. If subscription is ACTIVE, redirects to /stores (skip onboarding).
 * 3. If business profile is incomplete (default name or missing address), shows Step 1.
 * 4. Otherwise, shows Step 2 (Payment/Card validation).
 */

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useSession } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useI18n } from "@/components/lang/i18n-provider";
import {
  CreditCard,
  Shield,
  ArrowRight,
  CheckCircle2,
<<<<<<< HEAD
  Loader2,
  XCircle,
  Building2,
} from "lucide-react";
=======
  XCircle,
  Building2,
} from "lucide-react";
import { LottieLoader } from "@/components/ui/lottie-loader";
>>>>>>> dev
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Input } from "@/components/ui/input";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

// ============================================================================
// CONSTANTS
// ============================================================================

/** Default business name auto-generated by the store creation API */
const DEFAULT_BUSINESS_NAME = "My Business";

/** Shared container styles for both steps */
const CONTAINER_STYLES =
  "flex min-h-screen flex-col items-center justify-center bg-gray-50/30 px-4 py-12 md:px-8";
const CONTENT_WRAPPER_STYLES =
  "animate-in fade-in slide-in-from-bottom-4 w-full max-w-2xl duration-700";
const CARD_STYLES =
  "shadow-brand-primary/5 overflow-hidden border-0 shadow-2xl ring-1 ring-gray-200/60";
const CARD_CONTENT_STYLES = "p-8 md:p-12";
const INPUT_STYLES =
  "focus:border-brand-primary focus:ring-brand-primary/10 h-14 rounded-xl border-gray-200 bg-gray-50/50 px-4 text-base transition-all focus:bg-white focus:ring-4";
const BUTTON_STYLES =
  "group bg-brand-primary shadow-brand-primary/20 hover:bg-brand-primary/90 hover:shadow-brand-primary/30 h-14 w-full rounded-xl text-base font-semibold text-white shadow-lg transition-all hover:translate-y-[1px]";

// ============================================================================
// SCHEMA
// ============================================================================

/** Schema for the business setup form (Step 1) */
const setupSchema = z.object({
  name: z.string().min(2, "Business name is required").max(100),
  address: z.string().min(5, "Address is required").max(200),
});

type SetupInput = z.infer<typeof setupSchema>;

// ============================================================================
// COMPONENT
// ============================================================================

export function OnboardingContent() {
  const { t } = useI18n();
  const router = useRouter();
  const searchParams = useSearchParams();
  const { data: session, isPending: isSessionPending } = useSession();
  const isAuthenticated = !isSessionPending && !!session?.user;

  // Payment states
  const [isPaymentLoading, setIsPaymentLoading] = useState(false);
  const [paymentError, setPaymentError] = useState<string | null>(null);
  const wasCanceled = searchParams.get("canceled") === "true";

  // Business Profile Check State
  const [hasBusinessProfile, setHasBusinessProfile] = useState<boolean | null>(null);
  const [isCheckingProfile, setIsCheckingProfile] = useState(true);
  const [isCreatingProfile, setIsCreatingProfile] = useState(false);

  // -------------------------------------------------------------------------
  // EFFECTS
  // -------------------------------------------------------------------------

  // Check profile and subscription status on mount
  useEffect(() => {
    async function checkProfile() {
      if (!isAuthenticated) return;

      try {
        setIsCheckingProfile(true);
        const res = await fetch("/api/user/profile");

        if (res.ok) {
          const responseData = await res.json();
          const profile = responseData.data;
          const business = profile.business;
          const subscription = profile.subscription;

          // 1. SUBSCRIPTION CHECK - Skip onboarding if already active
          if (subscription?.status === "ACTIVE") {
            toast.success("Welcome back! Redirecting to your stores...");
            router.push("/stores");
            return;
          }

          // 2. BUSINESS PROFILE STRICT CHECK
          // Incomplete if: no business, default name, or missing address
          const isDefaultName = business?.name === DEFAULT_BUSINESS_NAME;
          const isAddressMissing = !business?.address || business.address.trim() === "";

          setHasBusinessProfile(!(!business || isDefaultName || isAddressMissing));
        } else {
          setHasBusinessProfile(false);
        }
      } catch (error) {
        console.error("Failed to check profile", error);
        setHasBusinessProfile(false);
      } finally {
        setIsCheckingProfile(false);
      }
    }

    checkProfile();
  }, [isAuthenticated, router]);

  // Redirect to login if not authenticated
  useEffect(() => {
    if (!isSessionPending && !isAuthenticated) {
      router.push("/login?callbackUrl=/onboarding");
    }
  }, [isSessionPending, isAuthenticated, router]);

  // -------------------------------------------------------------------------
  // FORM
  // -------------------------------------------------------------------------

  const form = useForm<SetupInput>({
    resolver: zodResolver(setupSchema),
    defaultValues: {
      name: "",
      address: "",
    },
  });

  // -------------------------------------------------------------------------
  // HANDLERS
  // -------------------------------------------------------------------------

  /** Handler for business setup submission (PATCH /api/user/business - Upsert) */
  const onSetupSubmit = async (data: SetupInput) => {
    setIsCreatingProfile(true);
    try {
      const res = await fetch("/api/user/business", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name: data.name,
          address: data.address,
        }),
      });

      if (!res.ok) {
        const errData = await res.json();
        throw new Error(errData.error?.message || "Failed to create business profile");
      }

      toast.success(t("onboarding.businessSetup.profileCreated"));
      setHasBusinessProfile(true);
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to create profile");
    } finally {
      setIsCreatingProfile(false);
    }
  };

  /** Handler for starting payment/card validation flow */
  const handleStartSetup = async () => {
    setIsPaymentLoading(true);
    setPaymentError(null);

    try {
      const response = await fetch("/api/subscriptions/setup", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error?.message || "Failed to start card validation");
      }

      if (data.data?.url) {
        window.location.href = data.data.url;
      } else {
        throw new Error("No checkout URL returned");
      }
    } catch (err) {
      setPaymentError(err instanceof Error ? err.message : "Something went wrong");
      setIsPaymentLoading(false);
    }
  };

  // -------------------------------------------------------------------------
  // RENDER HELPERS
  // -------------------------------------------------------------------------

  const isLoadingGlobal = isSessionPending || isCheckingProfile;

  /** Reusable Header component with step indicator */
  const Header = ({ step, title, subtitle }: { step: number; title: string; subtitle: string }) => (
    <div className="mb-10 text-center">
      {/* Visual Step Indicator */}
      <div className="mx-auto mb-6 flex max-w-[120px] items-center justify-center gap-2">
        <div
          className={cn(
            "h-2.5 w-2.5 rounded-full transition-colors duration-500",
            step >= 1 ? "bg-brand-primary" : "bg-gray-200"
          )}
        />
        <div
          className={cn(
            "h-0.5 flex-1 transition-colors duration-500",
            step >= 2 ? "bg-brand-primary" : "bg-gray-200"
          )}
        />
        <div
          className={cn(
            "h-2.5 w-2.5 rounded-full transition-colors duration-500",
            step >= 2 ? "bg-brand-primary" : "bg-gray-200"
          )}
        />
      </div>

      <div className="bg-brand-primary/5 ring-brand-primary/10 mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl shadow-sm ring-1">
        {step === 1 ? (
          <Building2 className="text-brand-primary h-8 w-8" strokeWidth={1.5} />
        ) : (
          <CreditCard className="text-brand-primary h-8 w-8" strokeWidth={1.5} />
        )}
      </div>

      <h1 className="text-brand-primary text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>
      <p className="mx-auto mt-3 max-w-sm text-base leading-relaxed text-gray-500">{subtitle}</p>
    </div>
  );

  // -------------------------------------------------------------------------
  // RENDER: LOADING STATE
  // -------------------------------------------------------------------------

  if (isLoadingGlobal) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-gray-50/50">
<<<<<<< HEAD
        <Loader2 className="text-brand-primary/80 h-10 w-10 animate-spin" />
=======
        <LottieLoader size="lg" />
>>>>>>> dev
        <p className="mt-4 text-sm font-medium text-gray-500">Loading your profile...</p>
      </div>
    );
  }

  // -------------------------------------------------------------------------
  // RENDER: STEP 1 - BUSINESS SETUP FORM
  // -------------------------------------------------------------------------

  if (hasBusinessProfile === false) {
    return (
      <div className={CONTAINER_STYLES}>
        <div className={CONTENT_WRAPPER_STYLES}>
          <Header
            step={1}
            title={t("onboarding.businessSetup.title")}
            subtitle={t("onboarding.businessSetup.subtitle")}
          />

          <Card className={CARD_STYLES}>
            <CardContent className={CARD_CONTENT_STYLES}>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSetupSubmit)} className="space-y-8">
                  <div className="grid gap-6">
                    <FormField
                      control={form.control}
                      name="name"
                      render={({ field }) => (
                        <FormItem className="space-y-3">
                          <FormLabel className="text-sm font-semibold text-gray-700">
                            {t("onboarding.businessSetup.businessName")}
                          </FormLabel>
                          <FormControl>
                            <Input
                              placeholder={t("onboarding.businessSetup.businessNamePlaceholder")}
                              className={INPUT_STYLES}
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name="address"
                      render={({ field }) => (
                        <FormItem className="space-y-3">
                          <FormLabel className="text-sm font-semibold text-gray-700">
                            {t("onboarding.businessSetup.businessAddress")}
                          </FormLabel>
                          <FormControl>
                            <Input
                              placeholder={t("onboarding.businessSetup.businessAddressPlaceholder")}
                              className={INPUT_STYLES}
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>

                  <div className="pt-2">
                    <Button type="submit" disabled={isCreatingProfile} className={BUTTON_STYLES}>
                      {isCreatingProfile ? (
                        <>
<<<<<<< HEAD
                          <Loader2 className="mr-2 h-5 w-5 animate-spin" />
=======
                          <LottieLoader size="sm" />
>>>>>>> dev
                          {t("onboarding.businessSetup.savingProfile")}
                        </>
                      ) : (
                        <>
                          {t("onboarding.businessSetup.continueButton")}
                          <ArrowRight className="ml-2 h-5 w-5 transition-transform duration-300 group-hover:translate-x-1" />
                        </>
                      )}
                    </Button>
                  </div>
                </form>
              </Form>
            </CardContent>
          </Card>

          <p className="mt-8 text-center text-xs text-gray-400">
            {t("onboarding.businessSetup.stepIndicator")}
          </p>
        </div>
      </div>
    );
  }

  // -------------------------------------------------------------------------
  // RENDER: STEP 2 - PAYMENT SETUP
  // -------------------------------------------------------------------------

  return (
    <div className={CONTAINER_STYLES}>
      <div className={CONTENT_WRAPPER_STYLES}>
        <Header step={2} title={t("onboarding.title")} subtitle={t("onboarding.subtitle")} />

        {/* Canceled Warning */}
        {wasCanceled && (
          <div className="mb-6 flex items-start gap-4 rounded-2xl border border-yellow-200 bg-yellow-50/80 p-5 backdrop-blur-sm">
            <XCircle className="mt-1 h-5 w-5 flex-shrink-0 text-yellow-600" />
            <div className="space-y-1">
              <p className="font-semibold text-yellow-800">{t("onboarding.canceledTitle")}</p>
              <p className="text-sm leading-relaxed text-yellow-700">
                {t("onboarding.canceledMessage")}
              </p>
            </div>
          </div>
        )}

        <Card className={CARD_STYLES}>
          <CardContent className={CARD_CONTENT_STYLES}>
            {/* Features List */}
            <div className="mb-10 space-y-5">
              <p className="text-sm font-semibold tracking-wider text-gray-500 uppercase">
                {t("onboarding.whatYouGet")}
              </p>
              <div className="grid gap-4 sm:grid-cols-2">
                {[
                  t("onboarding.features.fullAccess"),
                  t("onboarding.features.unlimited"),
                  t("onboarding.features.analytics"),
                  t("onboarding.features.emailSupport"),
                ].map((feature, i) => (
                  <div key={i} className="flex items-center gap-3 text-gray-700">
                    <div className="flex h-6 w-6 items-center justify-center rounded-full bg-green-100/80 text-green-600 shadow-sm">
                      <CheckCircle2 className="h-4 w-4" strokeWidth={3} />
                    </div>
                    <span className="text-sm font-medium">{feature}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Why card is needed Box */}
            <div className="mb-8 rounded-2xl bg-gray-50/80 p-6 ring-1 ring-gray-200/50">
              <div className="flex items-start gap-5">
                <div className="bg-brand-primary/10 rounded-xl p-2.5 shadow-sm">
                  <CreditCard className="text-brand-primary h-6 w-6" strokeWidth={2} />
                </div>
                <div>
                  <p className="font-semibold text-gray-900">{t("onboarding.whyCard")}</p>
                  <p className="mt-1.5 max-w-lg text-sm leading-relaxed text-gray-600">
                    {t("onboarding.whyCardExplanation")}
                  </p>
                </div>
              </div>
            </div>

            {/* Error Message */}
            {paymentError && (
              <div className="mb-6 rounded-xl bg-red-50 p-4 text-center text-sm font-medium text-red-600 ring-1 ring-red-100">
                {paymentError}
              </div>
            )}

            {/* Main CTA Button */}
            <Button
              onClick={handleStartSetup}
              disabled={isPaymentLoading}
              className={cn(BUTTON_STYLES, "relative overflow-hidden")}
            >
              <div className="relative z-10 flex items-center justify-center gap-2">
                {isPaymentLoading ? (
                  <>
<<<<<<< HEAD
                    <Loader2 className="h-5 w-5 animate-spin" />
=======
                    <LottieLoader size="sm" />
>>>>>>> dev
                    <span>{t("onboarding.pleaseWait")}</span>
                  </>
                ) : (
                  <>
                    <CreditCard className="h-5 w-5" />
                    <span>{t("onboarding.addCardButton")}</span>
                    <ArrowRight className="h-5 w-5 opacity-70 transition-transform duration-300 group-hover:translate-x-1" />
                  </>
                )}
              </div>
            </Button>

            {/* Security Note */}
            <div className="mt-8 flex items-center justify-center gap-2 text-xs text-gray-400">
              <Shield className="h-3.5 w-3.5" />
              <span>{t("onboarding.securedBy")}</span>
            </div>

            {/* Divider */}
            <div className="my-8 border-t border-gray-100" />

            {/* Skip Link */}
            <div className="text-center">
              <button
                onClick={() => router.push("/stores")}
                className="text-sm font-medium text-gray-400 transition-colors hover:text-gray-600 hover:underline hover:decoration-gray-300 hover:underline-offset-4"
              >
                {t("onboarding.skipButton")}
              </button>
            </div>
          </CardContent>
        </Card>

        <p className="mt-8 text-center text-xs text-gray-400">{t("onboarding.stepIndicator")}</p>
      </div>
    </div>
  );
}
